# AI Provider Library Imports
from openai import OpenAI
from google import genai
import os

# --- Text Generator Classes ---

class OpenAIGenerator:
    """
    Encapsulates the logic to interact with the OpenAI API.
    This class handles sending a prompt to a specific OpenAI model (e.g., GPT-4o)
    and returning the generated response.
    """
    def __init__(self, model_name="gpt-4o"):
        """
        Initializes the OpenAI client.

        Args:
            model_name (str): The identifier of the OpenAI model to use.
                              Defaults to "gpt-4o", a powerful and recent model.
        """
        self.model_name = model_name
        # Create an OpenAI client instance. The API key is automatically fetched
        # from the OPENAI_API_KEY environment variable.
        self.client = OpenAI()

    def generate(self, prompt):
        """
        Sends a prompt to the OpenAI model and returns the generated text.

        Args:
            prompt (str): The input text provided as instruction to the model.

        Returns:
            str: The text content of the response generated by the model.
        """
        print(f"Generando con OpenAI ({self.model_name})...")
        # Call the `create` method of the API's `chat.completions` endpoint.
        chat_completion = self.client.chat.completions.create(
            messages=[
                {
                    "role": "user",  # Define the role as "user" to indicate user input.
                    "content": prompt
                }
            ],
            model=self.model_name,
        )
        # The response is a complex object; extract the message content from the first choice.
        return chat_completion.choices[0].message.content

class GeminiGenerator:
    """
    Encapsulates the logic to interact with the Google Gemini API using the `google-genai` SDK.
    """
    def __init__(self, model_name="gemini-2.5-flash"):
        """
        Initializes the Gemini client.

        Args:
            model_name (str): The identifier of the model to use.
        """
        self.model_name = model_name
        self.client = None
        self._initialize_client()

    def _initialize_client(self):
        """Attempts to initialize the client using the environment API Key."""
        api_key = os.getenv("GOOGLE_API_KEY_FOR_GEMINI")
        if api_key:
            try:
                self.client = genai.Client(api_key=api_key)
            except Exception as e:
                print(f"Error al inicializar cliente Gemini: {e}")

    def generate(self, prompt):
        """
        Sends a prompt to the Gemini model and returns the generated text.

        Args:
            prompt (str): The input text.

        Returns:
            str: The response text.
        """
        if not self.client:
            self._initialize_client()
            if not self.client:
                return "Error: Cliente de Gemini no inicializado (falta API Key GOOGLE_API_KEY_FOR_GEMINI)."

        print("Generando con Gemini...")
        try:
            # The new SDK uses client.models.generate_content
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt
            )
            return response.text
        except Exception as e:
            return f"Error en generación con Gemini: {e}"

# --- AI Agent Class ---

class IAAgent:
    """
    Acts as an intermediary or "agent" that utilizes a text generator
    (such as OpenAIGenerator or GeminiGenerator) to perform more complex and specific tasks.
    This abstraction allows easily swapping the underlying AI engine without altering
    the task logic (e.g., generating a Google Dork).
    """
    def __init__(self, generator):
        """
        Initializes the agent with a specific text generation strategy.

        Args:
            generator: An instance of a generator class (e.g., `OpenAIGenerator()`).
                       This implements the "Strategy" design pattern.
        """
        self.generator = generator

    def generate_gdork(self, description):
        """
        Generates an optimized Google Dork from a natural language description.

        Args:
            description (str): The user-provided description of what to find.

        Returns:
            str: The generated Google Dork as a string, or None if an error occurs.
        """
        # Build a detailed, task-specific prompt for generating dorks.
        prompt = self._build_prompt(description)
        try:
            # Delegate text generation to the generator provided during initialization.
            output = self.generator.generate(prompt)
            return output
        except Exception as e:
            # Catch and handle any errors that occur during the API call.
            print(f'Error al generar el Google Dork: {e}')
            return None

    def _build_prompt(self, description):
        """
        Creates a structured prompt to guide the AI model.

        This method is crucial for prompt engineering. It provides the model
        with clear context, precise instructions, and examples (few-shot learning)
        to significantly improve the quality and formatting of the response.

        Args:
            description (str): The raw user description.

        Returns:
            str: The complete formatted prompt to be sent to the AI model.
        """
        # The multi-line f-string defines the prompt template.
        return f'''
        Tu tarea es actuar como un experto en OSINT y generar un Google Dork preciso y efectivo
        basado en la descripción proporcionada por el usuario. Un Google Dork utiliza operadores
        de búsqueda avanzada para encontrar información específica que no es fácilmente accesible
        mediante búsquedas convencionales.

        Instrucciones:
        1.  Analiza la descripción del usuario para identificar las palabras clave, los tipos de archivo,
            los dominios y cualquier otra restricción.
        2.  Traduce estos requisitos a los operadores de Google correspondientes (ej. `site:`, `filetype:`, `inurl:`, `intitle:`, etc.).
        3.  Combina los operadores de forma lógica para crear un dork cohesivo y eficiente.
        4.  Devuelve únicamente el dork generado, sin explicaciones adicionales.

        Ejemplos:

        Descripción del usuario: "Encuentra informes anuales en formato PDF de la empresa Microsoft."
        Google Dork: filetype:pdf "informe anual" site:microsoft.com

        Descripción del usuario: "Busca páginas de login de administrador en sitios educativos de Colombia."
        Google Dork: site:.edu.co intitle:"admin login" | inurl:"admin"

        Descripción del usuario: "Quiero encontrar hojas de cálculo de Excel que contengan listas de precios de productos electrónicos."
        Google Dork: filetype:xlsx "lista de precios" "productos electrónicos"

        Ahora, genera el Google Dork para la siguiente descripción:

        Descripción del usuario: "{description}"
        '''
