# Standard and third-party library imports
import requests  # To make HTTP requests and get webpage content.
from bs4 import BeautifulSoup  # To parse HTML and extract information.
from core.ai_agent import IAAgent, GeminiGenerator  # Imports classes to interact with AI.
import time
import os
from pyvis.network import Network
from core.config import DIR_GRAPHS

def get_text_from_url(url):
    """
    Extracts and cleans the text content of a webpage.

    This function downloads the HTML of a URL, parses it with BeautifulSoup,
    and removes non-visible elements (like scripts and styles) to leave
    only the readable text.

    Args:
        url (str): The web address to extract text from.

    Returns:
        str: The clean text of the webpage, or None if an error occurs.
    """
    try:
        # User-Agent headers are set to simulate a real browser.
        # This helps avoid blocks from websites that reject basic automated requests.
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        # Performs an HTTP GET request to the URL.
        # The timeout ensures the program doesn't hang indefinitely if the server doesn't respond.
        response = requests.get(url, headers=headers, timeout=15)
        # Raises an exception for HTTP error codes (e.g., 404 Not Found, 500 Internal Server Error).
        response.raise_for_status()
        
        # Initializes BeautifulSoup to parse the HTML using the standard 'html.parser'.
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Finds and removes all <script> and <style> tags, as their content is not readable text.
        for script_or_style in soup(["script", "style"]):
            script_or_style.decompose()  # decompose() completely deletes the element from the tree.
            
        # Extracts all text from the cleaned HTML.
        text = soup.get_text()
        
        # Processes the text to improve readability:
        # 1. Separates the text by lines and removes spaces at the beginning and end of each line (strip).
        lines = (line.strip() for line in text.splitlines())
        # 2. Separates lines by multiple spaces and strips again.
        chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
        # 3. Joins the non-empty fragments with a line break.
        clean_text = '\n'.join(chunk for chunk in chunks if chunk)
        
        return clean_text
    except requests.exceptions.RequestException as e:
        # Captures and logs any error during the extraction process (network issues, invalid URL, etc.).
        print(f"Error extracting text from {url}: {e}")
        return None
    except Exception as e:
        # Captures any other unexpected error during the process.
        print(f"An unexpected error occurred while processing the URL: {e}")
        return None

def _build_summary_prompt(text):
    """
    Helper function to build the prompt for text summarization.
    """
    return f"Please summarize the following text extracted from a webpage:\n\n---\n{text}\n---"

def summarize_text_with_ia(text, ia_agent):
    """
    Uses an AI Agent to generate a summary of the provided text.

    Args:
        text (str): The text to summarize.
        ia_agent (IAAgent): The initialized AI agent.

    Returns:
        str: The summary generated by the AI, or an error/warning message.
    """
    if not text:
        return "No text provided for summarization."

    # Limits the text size to avoid exceeding the AI model's token limit.
    # 30,000 characters is a safe approximation for current limits.
    max_chars = 30000 
    if len(text) > max_chars:
        # Truncates the text and adds a notice.
        text = text[:max_chars] + "... [Text truncated, too long]"

    try:
        # Generates the prompt and calls the AI agent's generate text method.
        prompt = _build_summary_prompt(text)
        summary = ia_agent.generator.generate(prompt)
        return summary if summary else "Could not generate a summary."
    except Exception as e:
        return f"Error interacting with the AI: {e}"

def _build_translation_analysis_prompt(text):
    """
    Helper function to build the prompt for translation and analysis.
    """
    return f'''
        Act as an expert OSINT analyst. Analyze the following extracted text from a website
        and provide a detailed summary of its content. Highlights the key points.
        The text may be somewhat messy due to extraction, so infer the context.

        TEXT:
        {text}
        '''

def translate_and_analyze_with_ia(text, ia_agent):
    """
    Translates and analyzes text from an unknown context or language.
    
    Args:
        text (str): The text to translate/analyze.
        ia_agent (IAAgent): AI agent to perform the task.
        
    Returns:
        str: The AI's response in Spanish.
    """
    if not text:
        return "No text provided for translation/analysis."

    max_chars = 30000 
    if len(text) > max_chars:
        text = text[:max_chars] + "... [Text truncated, too long]"

    try:
        prompt = _build_translation_analysis_prompt(text)
        resultado = ia_agent.generator.generate(prompt)
        return resultado if resultado else "Could not generate the analysis and translation."
    except Exception as e:
        return f"Error interacting with the AI: {e}"

def extract_entities_and_graph(text, ia_agent, output_filename="grafo.html"):
    """
    Uses AI to analyze text, extract relationships between entities (people, organizations, locations, domains, emails),
    and generates an interactive graph using Pyvis.
    
    Args:
        text (str): Source text for the analysis.
        ia_agent (IAAgent): AI Agent logic.
        output_filename (str): Name of the generated HTML file.
        
    Returns:
        str: Full path to the generated HTML file, or None if it fails.
    """
    output_filename = os.path.join(DIR_GRAPHS, os.path.basename(output_filename))
    if not text:
        print("[bold red]No text to analyze.[/bold red]")
        return None

    max_chars = 25000 
    if len(text) > max_chars:
        text = text[:max_chars] + "... [Text truncated]"

    prompt = f'''
    Act as an OSINT Intelligence Analyst. Read the following text and extract the relationships between different entities.
    An entity can be a Person, an Organization, a Location, a Website/Domain, an Email, or a Technology.
    
    I need you to return ONLY a list of relationships in plain text with exactly this format, one relationship per line:
    [Entity 1] | [Type of entity 1] | [Relationship description] | [Entity 2] | [Type of entity 2]
    
    Example:
    John Doe | Person | works at | Tech Corp | Organization
    Tech Corp | Organization | located in | New York | Location
    admin@example.com | Email | belongs to | John Doe | Person
    
    Do NOT use Markdown blocks. DO NOT write anything other than the list with the pipe (|) separators.
    If you find no relationships, respond with "NO_RELATIONSHIPS".
    
    Source Text:
    {text}
    '''

    try:
        response_text = ia_agent.generator.generate(prompt)
        if not response_text or response_text.strip() == "NO_RELATIONSHIPS":
            print("[yellow]No sufficient entities were identified for the graph.[/yellow]")
            return None
            
        # 2. Parse the AI response and build the graph
        # Create the network, configuring physics for a better layout
        net = Network(height="750px", width="100%", bgcolor="#222222", font_color="white", directed=True)
        
        # Assign colors to groups (Entity types)
        color_map = {
            'Persona': '#E57373', 'Person': '#E57373',
            'Organización': '#64B5F6', 'Organization': '#64B5F6',
            'Ubicación': '#81C784', 'Location': '#81C784',
            'Dominio': '#FFD54F', 'Website': '#FFD54F', 'Domain': '#FFD54F',
            'Email': '#BA68C8',
            'Tecnología': '#4DB6AC', 'Technology': '#4DB6AC'
        }
        
        lines = response_text.strip().split('\n')
        nodes_added = set()
        edges_added = 0
        
        for line in lines:
            parts = [p.strip() for p in line.split('|')]
            # Make sure the line has exactly 5 parts to consider it valid
            if len(parts) == 5:
                e1, t1, relation, e2, t2 = parts
                
                # Default colors if the type is not exactly recognized
                c1 = color_map.get(t1, "#FFFFFF")
                c2 = color_map.get(t2, "#FFFFFF")
                
                # Add nodes if they haven't been added yet
                if e1 not in nodes_added:
                    net.add_node(e1, label=e1, title=t1, color=c1)
                    nodes_added.add(e1)
                
                if e2 not in nodes_added:
                    net.add_node(e2, label=e2, title=t2, color=c2)
                    nodes_added.add(e2)
                
                # Add relationship (Edge)
                net.add_edge(e1, e2, title=relation, label=relation, color="#aaaaaa")
                edges_added += 1

        if edges_added == 0:
            print("[yellow]No relationships were identified to build the graph.[/yellow]")
            return None

        net.save_graph(output_filename)
        print(f"[green]Graph saved to:[/green] {output_filename}")
        return output_filename

    except Exception as e:
        print(f"[bold red]Error during entity extraction and graph generation:[/bold red] {e}")
        return None

# --- Example Execution Block ---
if __name__ == '__main__':
    """
    This block is executed only if the script is invoked directly.
    It serves as a usage demonstration and a quick test of the module's functionalities.
    """
    # Example URL for testing.
    test_url = "https://www.xataka.com/robotica-e-ia/gemini-1-5-pro-probamos-brutal-ia-google-que-analiza-documentos-videos-codigo-da-sopas-chatgpt-4"
    
    print(f"--- Getting text from: {test_url} ---")
    page_text = get_text_from_url(test_url)
    
    if page_text:
        print("\n--- Extracted text (first 500 characters) ---")
        print(page_text[:500])
        
        print("\n--- Generating summary with AI (Gemini) ---")
        # This block attempts to load the necessary dependencies and configuration
        # to instantiate the AI agent and generate a summary.
        try:
            from dotenv import load_dotenv
            import os
            from google import genai

            load_dotenv() # Loads environment variables (e.g., API key).
            GOOGLE_API_KEY_FOR_GEMINI = os.getenv("GOOGLE_API_KEY_FOR_GEMINI")
            
            if GOOGLE_API_KEY_FOR_GEMINI:
                # If the API key is available, configure the Gemini client.
                # (GeminiGenerator now handles client initialization with the key)
                pass
                # Creates instances of the generator and the agent.
                gemini_gen = GeminiGenerator()
                agent = IAAgent(gemini_gen)
                # Calls the summary function.
                resumen = summarize_text_with_ia(page_text, agent)
                print("\n--- Page Summary ---")
                print(resumen)
            else:
                # Warns the user if the API key is not configured.
                print("\nWarning: The GOOGLE_API_KEY_FOR_GEMINI key is not configured in .env.")
                print("Cannot generate summary.")

        except ImportError:
            print("\nWarning: Missing dependencies to run the full example (dotenv, google-generativeai).")
        except Exception as e:
            print(f"\nError durante el ejemplo de resumen: {e}")
